test:
  adapter: postgresql
  encoding: unicode
  database: soundclown_test
  pool: 5
  username: Dwoo
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: soundclown_production
  pool: 5
  username: Dwoo
  password:

development:
  adapter: postgresql
  encoding: unicode
  database: soundclown_development
  pool: 5
  username: Dwoo
  password:
